// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "Mi 10T";    // Network SSID (name)
const char PASS[]     = "Agualanjaron1";    // Network password (use for WPA, or use as key for WEP)

void onAlarmChange();

String message;
bool alarm;

void initProperties(){

  ArduinoCloud.addProperty(message, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(alarm, READWRITE, ON_CHANGE, onAlarmChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
